name: screva
description: A Video Call App , Made With Flutter Using Agora SDK

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  agora_uikit: ^0.0.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  loading_animation_widget: ^1.1.0+3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat.otf
